VillaWeb/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using VillaWeb.Infrastructures;
using VillaWeb.Models;
using VillaWeb.Models.Dto;
using VillaWeb.Services.IServices;

namespace VillaWeb.Controllers;

public class AuthController : Controller
{
    private readonly IAuthService _authService;
    private readonly ISignInService _signInService;
    public AuthController(IAuthService authService, ISignInService signInService)
    {
        _authService = authService;
        _signInService = signInService;
    }

    public IActionResult Login()
    {
        LoginRequestDTO model = new();
        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> Login(LoginRequestDTO model)
    {
        if (ModelState.IsValid) {
            var apiResponse = await _authService.LoginAsync<APIResponse>(model);

            if (apiResponse is not null) {
                if (apiResponse.IsSuccess) {
                    var tokenDTO = JsonConvert.DeserializeObject<TokenDTO>(Convert.ToString(apiResponse.Result));

                    await _signInService.SignInAsync(tokenDTO);

                    TempData["success"] = "You are logged in!";
                    return RedirectToAction("Index", "Home");
                } else {
                    ModelState.AddErrors(apiResponse.ErrorMessages);
                }
            } 
        }
        return View(model);
    }

    public IActionResult Register()
    {
        RegisterationRequestDTO model = new();
        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> Register(RegisterationRequestDTO model)
    {
        if (ModelState.IsValid) {
            var apiResponse = await _authService.RegisterAsync<APIResponse>(model);
            if (apiResponse is not null) {
                if (apiResponse.IsSuccess) {
                    TempData["success"] = "Your account was created successfully!";
                    return RedirectToAction("Login");
                } else {
                    ModelState.AddErrors(apiResponse.ErrorMessages);
                }
            } 
        }
        return View(model);
    }

    public async Task<IActionResult> Logout()
    {
        _signInService.SignOutAsync();
        return RedirectToAction("Index", "Home");
    }

    public IActionResult AccessDenied()
    {
        return View();
    }
}

VillaWeb/Controllers/VillaController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using VillaUtility;
using VillaWeb.Infrastructures;
using VillaWeb.Models;
using VillaWeb.Models.Dto;
using VillaWeb.Services.IServices;

namespace VillaWeb.Controllers;

public class VillaController : Controller
{
    private readonly IVillaService _villaService;
    private readonly IMapper _mapper;
    public VillaController(IVillaService villaService, IMapper mapper)
    {
        _villaService = villaService;
        _mapper = mapper;
    }

    public async Task<IActionResult> IndexVilla()
    {
        List<VillaDTO> list = new();
        var apiResponse = await _villaService.GetAllAsync<APIResponse>();

        if (apiResponse is not null && apiResponse.IsSuccess) {
            list = JsonConvert.DeserializeObject<List<VillaDTO>>(Convert.ToString(apiResponse.Result));
        }
        return View(list);
    }

    [Authorize(Roles = SD.Role.Admin)]
    public IActionResult CreateVilla()
    {
        return View();
    }

    [Authorize(Roles = SD.Role.Admin)]
    [HttpPost]
    public async Task<IActionResult> CreateVilla(VillaCreateDTO dto)
    {
        if (ModelState.IsValid) {
            var apiResponse = await _villaService.CreateAsync<APIResponse>(dto);

            if (apiResponse is not null ) {
                if (apiResponse.IsSuccess) {
                    TempData["success"] = "Villa created successfully!";
                    return RedirectToAction(nameof(IndexVilla));
                }
                // Error occurred
                ModelState.AddErrors(apiResponse.ErrorMessages);
            }
        }
        return View(dto);
    }
    [Authorize(Roles = SD.Role.Admin)]
    public async Task<IActionResult> UpdateVilla(int id)
    {
        var apiResponse = await _villaService.GetAsync<APIResponse>(id);
        if (apiResponse is not null && apiResponse.IsSuccess) {
            VillaDTO villaDTO = JsonConvert.DeserializeObject<VillaDTO>(Convert.ToString(apiResponse.Result));
            VillaUpdateDTO villaUpdateDTO = _mapper.Map<VillaUpdateDTO>(villaDTO);
            return View(villaUpdateDTO);
        }

        return NotFound();
    }
    [Authorize(Roles = SD.Role.Admin)]
    [HttpPost]
    public async Task<IActionResult> UpdateVilla(VillaUpdateDTO dto)
    {
        if (ModelState.IsValid) {
            var apiResponse = await _villaService.UpdateAsync<APIResponse>(dto);

            if (apiResponse is not null) {
                if (apiResponse.IsSuccess) {
                    TempData["success"] = "Villa updated successfully!";
                    return RedirectToAction(nameof(UpdateVilla), new { Id = dto.Id });
                }
                // Error occurred
                ModelState.AddErrors(apiResponse.ErrorMessages);
            }
        }
        return View(dto);
    }
    [Authorize(Roles = SD.Role.Admin)]
    [HttpPost]
    public async Task<IActionResult> DeleteVilla([FromForm]int id)
    {
        var apiResponse = await _villaService.DeleteAsync<APIResponse>(id);

        if (apiResponse is not null) {
            if (apiResponse.IsSuccess) {
                TempData["success"] = "Villa deleted successfully!";
                return RedirectToAction(nameof(IndexVilla));
            }
        }

        TempData["error"] = "Failed to delete this Villa!";
        return RedirectToAction(nameof(IndexVilla));
    }
}

VillaWeb/Controllers/VillaNumberController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using VillaWeb.Models;
using VillaWeb.Models.Dto;
using VillaWeb.Models.VM;
using VillaWeb.Services.IServices;
using VillaWeb.Infrastructures;
using Microsoft.AspNetCore.Authorization;
using VillaUtility;

namespace VillaWeb;
public class VillaNumberController : Controller
{
    private readonly IMapper _mapper;
    private readonly IVillaNumberService _villaNumberService;
    private readonly IVillaService _villaService;
    public VillaNumberController(IMapper mapper, IVillaNumberService villaNumberService, IVillaService villaService)
    {
        _mapper = mapper;
        _villaNumberService = villaNumberService;
        _villaService = villaService;
    }

    public async Task<IActionResult> IndexVillaNumber()
    {
        List<VillaNumberDTO> list = new();
        var apiResponse = await _villaNumberService.GetAllAsync<APIResponse>();

        if (apiResponse is not null && apiResponse.IsSuccess) {
            list = JsonConvert.DeserializeObject<List<VillaNumberDTO>>(Convert.ToString(apiResponse.Result));
        }
        return View(list);
    }

    [Authorize(Roles = SD.Role.Admin)]
    public async Task<IActionResult> CreateVillaNumber()
    {   
        VillaNumberCreateVM villaNumberVM = new();

        var villaApiResponse = await _villaService.GetAllAsync<APIResponse>();
        if (villaApiResponse is not null && villaApiResponse.IsSuccess) {
            var villas = JsonConvert.DeserializeObject<List<VillaDTO>>(Convert.ToString(villaApiResponse.Result));
            villaNumberVM.SelectListOfVillas = villas.Select(villa => new SelectListItem {
                Text = villa.Name,
                Value = villa.Id.ToString()
            });
        }
        
        return View(villaNumberVM);
    }

    [Authorize(Roles = SD.Role.Admin)]
    [HttpPost]
    public async Task<IActionResult> CreateVillaNumber(VillaNumberCreateVM villaNumberCreateVM)
    {
        if (ModelState.IsValid) {
            var apiResponse = await _villaNumberService.CreateAsync<APIResponse>(villaNumberCreateVM.VillaNumber);
            if (apiResponse is not null) {
                if (apiResponse.IsSuccess) {
                    TempData["success"] = "Villa Number created successfully!";
                    return RedirectToAction(nameof(IndexVillaNumber));
                } else {
                    ModelState.AddErrors(apiResponse.ErrorMessages);
                }
            }
        }

        // Load the select list of villas
        var villaApiResponse = await _villaService.GetAllAsync<APIResponse>();
        if (villaApiResponse is not null && villaApiResponse.IsSuccess) {
            var villas = JsonConvert.DeserializeObject<List<VillaDTO>>(Convert.ToString(villaApiResponse.Result));
            villaNumberCreateVM.SelectListOfVillas = villas.Select(villa => new SelectListItem {
                Text = villa.Name,
                Value = villa.Id.ToString()
            });
        }
        return View(villaNumberCreateVM);
    }

    [Authorize(Roles = SD.Role.Admin)]
    public async Task<IActionResult> UpdateVillaNumber(int id)
    {   
        // Get the villa number with specified id
        APIResponse? villaNumberApiResponse = await _villaNumberService.GetAsync<APIResponse>(id);
        if (villaNumberApiResponse is not null && villaNumberApiResponse.IsSuccess) {
            VillaNumberDTO villaNumber = JsonConvert.DeserializeObject<VillaNumberDTO>(Convert.ToString(villaNumberApiResponse.Result));
            
            VillaNumberUpdateDTO updateDto = _mapper.Map<VillaNumberUpdateDTO>(villaNumber);
            VillaNumberUpdateVM villaNumberVM = new() {
                VillaNumber = updateDto
            };

            var villaApiResponse = await _villaService.GetAllAsync<APIResponse>();
            if (villaApiResponse is not null && villaApiResponse.IsSuccess) {
                var villas = JsonConvert.DeserializeObject<List<VillaDTO>>(Convert.ToString(villaApiResponse.Result));
                villaNumberVM.SelectListOfVillas = villas.Select(villa => new SelectListItem {
                    Text = villa.Name,
                    Value = villa.Id.ToString()
                });
            }
            return View(villaNumberVM);
        }
        return NotFound();    
    }

    [Authorize(Roles = SD.Role.Admin)]
    [HttpPost]
    public async Task<IActionResult> UpdateVillaNumber(VillaNumberUpdateVM villaNumberUpdateVM)
    {
        if (ModelState.IsValid) {
            var apiResponse = await _villaNumberService.UpdateAsync<APIResponse>(villaNumberUpdateVM.VillaNumber);
            if (apiResponse is not null) {
                if (apiResponse.IsSuccess) {
                    TempData["success"] = "Villa Number updated successfully!";
                    return RedirectToAction(nameof(IndexVillaNumber));
                } else {
                    ModelState.AddErrors(apiResponse.ErrorMessages);
                }
            }
        }

        // Load the select list of villas
        var villaApiResponse = await _villaService.GetAllAsync<APIResponse>();
        if (villaApiResponse is not null && villaApiResponse.IsSuccess) {
            var villas = JsonConvert.DeserializeObject<List<VillaDTO>>(Convert.ToString(villaApiResponse.Result));
            villaNumberUpdateVM.SelectListOfVillas = villas.Select(villa => new SelectListItem {
                Text = villa.Name,
                Value = villa.Id.ToString()
            });
        }
        return View(villaNumberUpdateVM);
    }
    
    [Authorize(Roles = SD.Role.Admin)]
    [HttpPost]
    public async Task<IActionResult> DeleteVillaNumber([FromForm]int id)
    {
        var apiResponse = await _villaNumberService.DeleteAsync<APIResponse>(id);

        if (apiResponse is not null && apiResponse.IsSuccess) {
            TempData["success"] = "Villa Number deleted successfully!";
            return RedirectToAction(nameof(IndexVillaNumber));
        }

        TempData["error"] = "Failed to delete this Villa Number!";
        return RedirectToAction(nameof(IndexVillaNumber));
    }
}

VillaWeb/Views/Shared/_BootstrapValidationStyle.cshtml
<script type="text/javascript">
    window.addEventListener("DOMContentLoaded", () => {
        document.querySelectorAll("input.input-validation-error").forEach(
            (elem) => { elem.classList.add("is-invalid"); }
        );
    });
</script>

VillaWeb/Views/Shared/_Layout.cshtml
@inject IHttpContextAccessor HttpContextAccessor
@using VillaUtility

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VillaWeb</title>
    @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @* <link rel="stylesheet" href="~/css/cyborg-bootswatch.css" asp-append-version="true" /> *@
    <link rel="stylesheet" href="~/VillaWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Vinahouse</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole(SD.Role.Admin)) {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Villa" asp-action="IndexVilla">Villa</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="VillaNumber" asp-action="IndexVillaNumber">Villa Number</a>
                            </li>
                        }

                        <div class="d-flex ms-auto">
                            @if (User.Identity?.IsAuthenticated ?? false){
                                <li class="nav-item navbar-text">
                                    Hello @User.Identity.Name
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Auth" asp-action="LogOut">Logout</a>
                                </li>
                            } else {
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Auth" asp-action="Register">Register</a>
                                </li>
                            }
                        </div>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="pb-5">
        <main role="main" class="">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted bg-dark-subtle">
        <div class="container">
            &copy; 2024 - VillaWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @* <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> *@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    
    <partial name="_Notification" />
    <partial name="_BootstrapValidationStyle" />

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

VillaWeb/Views/Shared/_Notification.cshtml
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

@if (TempData["success"] is not null) {
    <script>
        const Toast = Swal.mixin({
            toast: true,
            position: "top-end",
            showConfirmButton: false,
            timer: 3000,
            timerProgressBar: true,
            didOpen: (toast) => {
                toast.onmouseenter = Swal.stopTimer;
                toast.onmouseleave = Swal.resumeTimer;
            }
            });
            Toast.fire({
            icon: "success",
            title: "@TempData["success"]"
        });
    </script>
}

@if (TempData["error"] is not null) {
    <script>
        const Toast = Swal.mixin({
            toast: true,
            position: "top-end",
            showConfirmButton: false,
            timer: 3000,
            timerProgressBar: true,
            didOpen: (toast) => {
                toast.onmouseenter = Swal.stopTimer;
                toast.onmouseleave = Swal.resumeTimer;
            }
            });
            Toast.fire({
            icon: "error",
            title: "@TempData["error"]"
        });
    </script>
}